-- ============================================
-- Watering Log App — Initial Setup
-- Run once on a fresh Supabase project.
-- ============================================


-- ============================================
-- TABLES
-- ============================================

create table public.watering_logs (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_email text null,
  plot_name text null,
  start_time timestamp with time zone null,
  end_time timestamp with time zone null,
  duration double precision null,
  start_photo_url text null,
  end_photo_url text null,
  issue_reason text null,
  constraint watering_logs_pkey primary key (id),
  constraint unique_watering_session unique (plot_name, start_time)
) TABLESPACE pg_default;

create table public.admins (
  email text not null,
  created_at timestamp with time zone not null default now(),
  constraint admins_pkey primary key (email)
) TABLESPACE pg_default;


-- ============================================
-- ROW LEVEL SECURITY
-- ============================================

alter table public.admins enable row level security;

create policy "Authenticated users can read admins"
on public.admins
for select
to authenticated
using (true);


-- ============================================
-- STORAGE BUCKET
-- Uncomment the INSERT if the bucket does not exist yet.
-- ============================================

-- insert into storage.buckets (id, name, public)
-- values ('watering-photos', 'watering-photos', true);

drop policy if exists "Give anon users access to JPG images in folder 1207hnn_1" on storage.objects;

create policy "Allow All Uploads"
on storage.objects
for insert
to public
with check (bucket_id = 'watering-photos');

create policy "Allow Public Viewing"
on storage.objects
for select
to public
using (bucket_id = 'watering-photos');


-- ============================================
-- SEED DATA
-- ============================================

insert into public.admins (email) values ('admin@admin.com');
