-- ============================================
-- Watering Log App — Initial Setup
-- Run once on a fresh Supabase project.
-- ============================================


-- ============================================
-- TABLES
-- ============================================

create table public.watering_logs (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_email text null,
  plot_name text null,
  start_time timestamp with time zone null,
  end_time timestamp with time zone null,
  duration double precision null,
  start_photo_url text null,
  end_photo_url text null,
  issue_reason text null,
  constraint watering_logs_pkey primary key (id),
  constraint unique_watering_session unique (plot_name, start_time)
) TABLESPACE pg_default;

create table public.admins (
  email text not null,
  created_at timestamp with time zone not null default now(),
  constraint admins_pkey primary key (email)
) TABLESPACE pg_default;


-- ============================================
-- ROW LEVEL SECURITY
-- ============================================

alter table public.admins enable row level security;

create policy "Authenticated users can read admins"
on public.admins
for select
to authenticated
using (true);


-- ============================================
-- STORAGE BUCKET
-- Uncomment the INSERT if the bucket does not exist yet.
-- ============================================

-- insert into storage.buckets (id, name, public)
-- values ('watering-photos', 'watering-photos', true);

drop policy if exists "Give anon users access to JPG images in folder 1207hnn_1" on storage.objects;

create policy "Allow All Uploads"
on storage.objects
for insert
to public
with check (bucket_id = 'watering-photos');

create policy "Allow Public Viewing"
on storage.objects
for select
to public
using (bucket_id = 'watering-photos');


-- ============================================
-- PERSISTENT PAYROLL INPUT STATE
-- These hold the current bibit counts and operator names.
-- They persist across months so admin doesn't re-type every month.
-- ============================================

create table public.plot_seedlings (
  plot_name text not null,
  seedling_count integer not null default 0,
  target_per_day integer not null default 0,
  updated_at timestamp with time zone not null default now(),
  updated_by text,
  constraint plot_seedlings_pkey primary key (plot_name)
) TABLESPACE pg_default;

create table public.area_operators (
  area_code text not null,
  operator_name text not null,
  updated_at timestamp with time zone not null default now(),
  updated_by text,
  constraint area_operators_pkey primary key (area_code)
) TABLESPACE pg_default;

alter table public.plot_seedlings enable row level security;
alter table public.area_operators enable row level security;

create policy "Authenticated users can read plot_seedlings"
on public.plot_seedlings for select to authenticated using (true);
create policy "Authenticated users can insert plot_seedlings"
on public.plot_seedlings for insert to authenticated with check (true);
create policy "Authenticated users can update plot_seedlings"
on public.plot_seedlings for update to authenticated using (true);

create policy "Authenticated users can read area_operators"
on public.area_operators for select to authenticated using (true);
create policy "Authenticated users can insert area_operators"
on public.area_operators for insert to authenticated with check (true);
create policy "Authenticated users can update area_operators"
on public.area_operators for update to authenticated using (true);

-- Seed initial operator names
insert into public.area_operators (area_code, operator_name) values
  ('BNN', 'Hasannudin'),
  ('UNN1', 'Salim'),
  ('UNN2', 'Lalu Fahri');


-- ============================================
-- MANAGEMENT SIGNATURES
-- 3 fixed roles. Holds the latest signing names, positions, and dates.
-- ============================================

create table public.management_signatures (
  role text not null,
  person_name text,
  position text,
  sig_date date,
  updated_at timestamp with time zone not null default now(),
  updated_by text,
  constraint management_signatures_pkey primary key (role)
) TABLESPACE pg_default;

alter table public.management_signatures enable row level security;

create policy "Authenticated users can read management_signatures"
on public.management_signatures for select to authenticated using (true);
create policy "Authenticated users can insert management_signatures"
on public.management_signatures for insert to authenticated with check (true);
create policy "Authenticated users can update management_signatures"
on public.management_signatures for update to authenticated using (true);

-- Seed 3 roles
insert into public.management_signatures (role) values
  ('prepared_by'),
  ('verified_by'),
  ('approved_by');


-- ============================================
-- PAYROLL CONFIG (key/value)
-- e.g. 'rate_per_unit' = '0.001'
-- ============================================

create table public.payroll_config (
  config_key text not null,
  config_value text,
  updated_at timestamp with time zone not null default now(),
  updated_by text,
  constraint payroll_config_pkey primary key (config_key)
) TABLESPACE pg_default;

alter table public.payroll_config enable row level security;

create policy "Authenticated users can read payroll_config"
on public.payroll_config for select to authenticated using (true);
create policy "Authenticated users can insert payroll_config"
on public.payroll_config for insert to authenticated with check (true);
create policy "Authenticated users can update payroll_config"
on public.payroll_config for update to authenticated using (true);

insert into public.payroll_config (config_key, config_value) values
  ('rate_per_unit', '0.001')
on conflict (config_key) do nothing;


-- ============================================
-- PAYROLL SNAPSHOTS
-- One row per (month) holds the saved claim breakdown for that month.
-- ============================================

create table public.payroll_snapshots (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  saved_by text null,
  snapshot_month text not null,
  snapshot_data jsonb not null,
  constraint payroll_snapshots_pkey primary key (id),
  constraint unique_snapshot_per_month unique (snapshot_month)
) TABLESPACE pg_default;

alter table public.payroll_snapshots enable row level security;

create policy "Authenticated users can read payroll snapshots"
on public.payroll_snapshots
for select
to authenticated
using (true);

create policy "Authenticated users can insert payroll snapshots"
on public.payroll_snapshots
for insert
to authenticated
with check (true);

create policy "Authenticated users can update payroll snapshots"
on public.payroll_snapshots
for update
to authenticated
using (true);

create policy "Authenticated users can delete payroll snapshots"
on public.payroll_snapshots
for delete
to authenticated
using (true);


-- ============================================
-- SEED DATA
-- ============================================

insert into public.admins (email) values ('admin@admin.com');
