-- ============================================================
-- Watering Log App — Full Setup for NEW Supabase Project
-- All custom tables/functions prefixed with "watering_".
-- (watering_logs already has the prefix, so it stays as-is.)
--
-- This file merges and replaces the two prior migrations:
--   - 20260519000000_initial_setup.sql
--   - 20260521000000_data_retention.sql
--
-- HOW TO USE on the new Supabase project:
--   1. Create the new project in Supabase dashboard.
--   2. Dashboard → Database → Extensions → enable pg_cron.
--   3. Dashboard → Storage → New bucket → name: "watering-photos" → public.
--   4. Dashboard → SQL Editor → paste this entire file → Run.
--   5. (If migrating data from the old project) see the "DATA MOVE" section at bottom.
-- ============================================================


-- ============================================================
-- 1. TABLES
-- ============================================================

-- Worker watering session logs (no prefix needed — already starts with watering_)
create table public.watering_logs (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_email text null,
  plot_name text null,
  start_time timestamp with time zone null,
  end_time timestamp with time zone null,
  duration double precision null,
  start_photo_url text null,
  end_photo_url text null,
  issue_reason text null,
  constraint watering_logs_pkey primary key (id),
  constraint watering_unique_session unique (plot_name, start_time)
) TABLESPACE pg_default;

-- Admins
create table public.watering_admins (
  email text not null,
  created_at timestamp with time zone not null default now(),
  constraint watering_admins_pkey primary key (email)
) TABLESPACE pg_default;

-- Field Coordinators
create table public.watering_field_coordinators (
  email text not null,
  created_at timestamp with time zone not null default now(),
  constraint watering_field_coordinators_pkey primary key (email)
) TABLESPACE pg_default;

-- Plot seedling counts + per-day target
create table public.watering_plot_seedlings (
  plot_name text not null,
  seedling_count integer not null default 0,
  target_per_day integer not null default 0,
  updated_at timestamp with time zone not null default now(),
  updated_by text,
  constraint watering_plot_seedlings_pkey primary key (plot_name)
) TABLESPACE pg_default;

-- Area-to-operator mapping
create table public.watering_area_operators (
  area_code text not null,
  operator_name text not null,
  updated_at timestamp with time zone not null default now(),
  updated_by text,
  constraint watering_area_operators_pkey primary key (area_code)
) TABLESPACE pg_default;

-- Management signature persons (3 fixed roles)
create table public.watering_management_signatures (
  role text not null,
  person_name text,
  position text,
  sig_date date,
  updated_at timestamp with time zone not null default now(),
  updated_by text,
  constraint watering_management_signatures_pkey primary key (role)
) TABLESPACE pg_default;

-- Payroll config (key/value, e.g. rate_per_unit)
create table public.watering_payroll_config (
  config_key text not null,
  config_value text,
  updated_at timestamp with time zone not null default now(),
  updated_by text,
  constraint watering_payroll_config_pkey primary key (config_key)
) TABLESPACE pg_default;

-- Payroll snapshots (one row per month — frozen claim form)
create table public.watering_payroll_snapshots (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  saved_by text null,
  snapshot_month text not null,
  snapshot_data jsonb not null,
  constraint watering_payroll_snapshots_pkey primary key (id),
  constraint watering_unique_snapshot_per_month unique (snapshot_month)
) TABLESPACE pg_default;


-- ============================================================
-- 2. ROW LEVEL SECURITY
-- ============================================================

alter table public.watering_logs enable row level security;
alter table public.watering_admins enable row level security;
alter table public.watering_field_coordinators enable row level security;
alter table public.watering_plot_seedlings enable row level security;
alter table public.watering_area_operators enable row level security;
alter table public.watering_management_signatures enable row level security;
alter table public.watering_payroll_config enable row level security;
alter table public.watering_payroll_snapshots enable row level security;

-- watering_logs: workers + admin insert; everyone reads/updates
create policy "Authenticated read watering_logs"
on public.watering_logs for select to authenticated using (true);
create policy "Authenticated insert watering_logs"
on public.watering_logs for insert to authenticated with check (true);
create policy "Authenticated update watering_logs"
on public.watering_logs for update to authenticated using (true);
create policy "Authenticated delete watering_logs"
on public.watering_logs for delete to authenticated using (true);

-- Read-only tables (admins, field_coordinators)
create policy "Authenticated read watering_admins"
on public.watering_admins for select to authenticated using (true);

create policy "Authenticated read watering_field_coordinators"
on public.watering_field_coordinators for select to authenticated using (true);

-- Read/insert/update tables
create policy "Authenticated read watering_plot_seedlings"
on public.watering_plot_seedlings for select to authenticated using (true);
create policy "Authenticated insert watering_plot_seedlings"
on public.watering_plot_seedlings for insert to authenticated with check (true);
create policy "Authenticated update watering_plot_seedlings"
on public.watering_plot_seedlings for update to authenticated using (true);

create policy "Authenticated read watering_area_operators"
on public.watering_area_operators for select to authenticated using (true);
create policy "Authenticated insert watering_area_operators"
on public.watering_area_operators for insert to authenticated with check (true);
create policy "Authenticated update watering_area_operators"
on public.watering_area_operators for update to authenticated using (true);

create policy "Authenticated read watering_management_signatures"
on public.watering_management_signatures for select to authenticated using (true);
create policy "Authenticated insert watering_management_signatures"
on public.watering_management_signatures for insert to authenticated with check (true);
create policy "Authenticated update watering_management_signatures"
on public.watering_management_signatures for update to authenticated using (true);

create policy "Authenticated read watering_payroll_config"
on public.watering_payroll_config for select to authenticated using (true);
create policy "Authenticated insert watering_payroll_config"
on public.watering_payroll_config for insert to authenticated with check (true);
create policy "Authenticated update watering_payroll_config"
on public.watering_payroll_config for update to authenticated using (true);

-- Payroll snapshots: read/insert/update/delete (delete for the 🗑️ button)
create policy "Authenticated read watering_payroll_snapshots"
on public.watering_payroll_snapshots for select to authenticated using (true);
create policy "Authenticated insert watering_payroll_snapshots"
on public.watering_payroll_snapshots for insert to authenticated with check (true);
create policy "Authenticated update watering_payroll_snapshots"
on public.watering_payroll_snapshots for update to authenticated using (true);
create policy "Authenticated delete watering_payroll_snapshots"
on public.watering_payroll_snapshots for delete to authenticated using (true);


-- ============================================================
-- 3. STORAGE BUCKET POLICIES
-- (Create the bucket "watering-photos" in Dashboard first.)
-- ============================================================

-- Optional: create bucket via SQL if not done via dashboard
-- insert into storage.buckets (id, name, public)
-- values ('watering-photos', 'watering-photos', true)
-- on conflict (id) do nothing;

create policy "Allow All Uploads to watering-photos"
on storage.objects
for insert
to public
with check (bucket_id = 'watering-photos');

create policy "Allow Public Viewing of watering-photos"
on storage.objects
for select
to public
using (bucket_id = 'watering-photos');

create policy "Allow Authenticated Delete of watering-photos"
on storage.objects
for delete
to authenticated
using (bucket_id = 'watering-photos');

-- NOTE: Supabase blocks direct DELETE FROM storage.objects via SQL (a safety
-- feature called protect_delete). So we cannot auto-delete photos via a trigger
-- or via the retention function below. Photo cleanup is wired via an
-- **Edge Function + Database Webhook** instead. See:
--   supabase/functions/delete-watering-photos/index.ts
-- Setup steps:
--   1. Install Supabase CLI: https://supabase.com/docs/guides/cli
--   2. supabase login   &&   supabase link --project-ref kibqjztozokohqmhqqqf
--   3. supabase functions deploy delete-watering-photos --no-verify-jwt
--   4. Dashboard → Database → Webhooks → Create a new hook:
--        Table:    watering_logs
--        Events:   Delete (only)
--        Type:     Supabase Edge Functions
--        Function: delete-watering-photos
-- Once wired, ANY delete of a watering_logs row (manual, cron, app-driven)
-- auto-deletes its photos from the watering-photos bucket.


-- ============================================================
-- 4. SEED DATA
-- (All use ON CONFLICT so re-running this file is safe.)
-- ============================================================

insert into public.watering_admins (email) values ('admin@admin.com')
on conflict (email) do nothing;

insert into public.watering_area_operators (area_code, operator_name) values
  ('BNN', 'Hasannudin'),
  ('UNN1', 'Salim'),
  ('UNN2', 'Lalu Fahri')
on conflict (area_code) do nothing;

insert into public.watering_management_signatures (role) values
  ('prepared_by'),
  ('verified_by'),
  ('approved_by')
on conflict (role) do nothing;

insert into public.watering_payroll_config (config_key, config_value) values
  ('rate_per_unit', '0.001')
on conflict (config_key) do nothing;


-- ============================================================
-- 5. DATA RETENTION (3-year auto-prune)
-- PREREQUISITE: pg_cron must be enabled first (see top of file).
-- ============================================================

create or replace function public.watering_prune_old_logs()
returns table(deleted_logs bigint, deleted_photo_refs bigint)
language plpgsql
security definer
set search_path = public, storage
as $$
declare
    cutoff_date timestamptz;
    logs_count bigint := 0;
begin
    cutoff_date := now() - interval '3 years';

    -- Delete the old log rows. The Database Webhook on watering_logs DELETE
    -- (see Storage section above) fires the delete-watering-photos Edge Function
    -- once per row, which removes the start/end photos from the bucket via the
    -- Storage Admin API. So this single DELETE cleans both rows AND photos.
    with deleted as (
        delete from public.watering_logs
         where end_time < cutoff_date
        returning 1
    )
    select count(*) into logs_count from deleted;

    return query select logs_count, 0::bigint;
end;
$$;

revoke execute on function public.watering_prune_old_logs() from public;
revoke execute on function public.watering_prune_old_logs() from anon;
revoke execute on function public.watering_prune_old_logs() from authenticated;

-- Schedule: daily at 16:00 UTC (= 00:00 Malaysia Time, low-traffic window)
select cron.schedule(
    'watering_prune_3y',
    '0 16 * * *',
    $$select public.watering_prune_old_logs();$$
);


-- ============================================================
-- DATA MOVE — instructions for migrating rows from the OLD project
-- ============================================================
--
-- After the schema above is created on the new project, populate it
-- with data from the old project. Two practical paths:
--
-- A) CSV export/import (simplest, low row count):
--    On OLD project SQL Editor:
--        SELECT * FROM admins;           -- → export as CSV
--        SELECT * FROM watering_logs;    -- → export as CSV
--        ...etc for each table
--    On NEW project SQL Editor, use Table Editor → Import CSV per table.
--    Match the new prefixed table names:
--        admins                    → watering_admins
--        field_coordinators        → watering_field_coordinators
--        plot_seedlings            → watering_plot_seedlings
--        area_operators            → watering_area_operators
--        management_signatures     → watering_management_signatures
--        payroll_config            → watering_payroll_config
--        payroll_snapshots         → watering_payroll_snapshots
--        watering_logs             → watering_logs   (no rename)
--
-- B) pg_dump (most thorough):
--    From a machine with psql/pg_dump installed, with the OLD project's
--    direct connection string:
--        pg_dump -h <old-host> -U postgres -d postgres \
--          --schema=public --data-only \
--          --table=admins --table=field_coordinators \
--          --table=plot_seedlings --table=area_operators \
--          --table=management_signatures --table=payroll_config \
--          --table=payroll_snapshots --table=watering_logs \
--          -f data.sql
--    Then edit data.sql to rename tables to the watering_ prefixed names
--    (search/replace 'public.admins' → 'public.watering_admins' etc.),
--    and run on the NEW project.
--
-- Storage photos: download from OLD bucket via Dashboard or `supabase storage`
-- CLI, upload to NEW bucket. URLs inside watering_logs already point to
-- "watering-photos/..." paths, so they'll keep working as long as the
-- new bucket has the same name.
--
-- ============================================================


-- ============================================================
-- USEFUL CHECK QUERIES
-- ============================================================
--   SELECT * FROM cron.job;                    -- see scheduled jobs
--   SELECT * FROM public.watering_admins;      -- verify admin seed
--   SELECT * FROM public.watering_prune_old_logs();   -- manual prune
